name: PvPEvent
author: Mickyjou
version: VERSION
main: de.mickyjou.plugins.pvpevent.PvPEventPlugin
depend: [PlayerDataStore]
commands:
     schematic:
          description: Main command for the Schematic Manager
     generate:
          description: Generates EventChunks with the size of 4x4 Chunks
     team:
          description: shows your team and create new teams
     teams:
          description: shows all teams
     warnings:
          description: Shows your warnings
     setspawn:
          description: Sets the Lobby-Spawn

     