name: PvPEvent
author: Mickyjou
version: VERSION
main: de.mickyjou.plugins.pvpevent.PvPEventPlugin
depend: [PlayerDataStore]
commands:
     team:
          description: shows your team and create new teams
     teams:
          description: shows all teams
     warnings:
          description: Shows your warnings
     setspawn:
          description: Sets the Lobby-Spawn
     sethologramm:
          description: Sets the Lobby-Hologramm
     ping:
          description: Shows Your Ping
     clearitem:
          descruption: Clears your Inventory from one Type
          aliases: [ci]
     setzombie:
          description: Sets the Spawn-Zombie
     chest:
          description: Main command for the Case-Opening in the Lobby
     compass:
     response:


     